import Foundation

/// Which section of the binder a generated file belongs in (§4.2).
public enum MatterSection: Sendable, Equatable {
    case front
    case back
}

/// The six standard front/back matter files (§9.2), generated from `project.json` at
/// project creation as editable markdown — never regenerated at compile time, so hand
/// edits are permanent. `content(for:)` is what "Regenerate from template" writes back.
///
/// Order and wording matched directly against the Rook Takes EPUB — the house style
/// for Drew Calloway books, which this app is built around (front: Title Page →
/// Copyright → Contents → Dedication; back: a review-ask page → Newsletter → About
/// the Author) — `Contents` isn't one of these six, since unlike the others its
/// content (the chapter list) isn't known until compile time; it's generated by
/// `EPUBTableOfContentsGenerator` and spliced in after Copyright.
public enum FrontBackMatterTemplate: String, CaseIterable, Sendable {
    case titlePage
    case copyright
    case dedication
    case reviewAsk
    case newsletter
    case aboutTheAuthor

    public var section: MatterSection {
        switch self {
        case .titlePage, .copyright, .dedication: return .front
        case .reviewAsk, .newsletter, .aboutTheAuthor: return .back
        }
    }

    /// Whether this template's own heading (`content(for:)`'s `#` line) is meant to be
    /// visible on the compiled page, matching the `.hidden-heading`/`.title-page-heading`
    /// split already encoded there: Copyright/Dedication/A Note From/Newsletter carry
    /// legal or ad-copy text of their own and never show their heading text, while Title
    /// Page (the book's actual title) and About the Author (a real section title) do.
    /// Print's Typst pipeline needs this explicitly (§ TypstDocumentGenerator) because
    /// pandoc's typst writer drops the CSS class `content(for:)` set the heading with —
    /// only the `#id` survives, as a Typst label.
    public var showsHeadingOnPage: Bool {
        switch self {
        case .copyright, .dedication, .reviewAsk, .newsletter: return false
        case .titlePage, .aboutTheAuthor: return true
        }
    }

    /// Filename with its ordering prefix (§4.3).
    public var filename: String {
        switch self {
        case .titlePage: return "01 Title Page.md"
        case .copyright: return "02 Copyright.md"
        case .dedication: return "03 Dedication.md"
        case .reviewAsk: return "01 A Note From the Author.md"
        case .newsletter: return "02 Newsletter.md"
        case .aboutTheAuthor: return "03 About the Author.md"
        }
    }

    /// The explicit anchor every template's heading carries (`{#id}`, below) — stable
    /// regardless of the heading's own text, so `EPUBTableOfContentsGenerator` can
    /// link to it without needing to reproduce pandoc's own heading-slug algorithm.
    public var anchorID: String {
        switch self {
        case .titlePage: return "title-page"
        case .copyright: return "copyright"
        case .dedication: return "dedication"
        case .reviewAsk: return "review-ask"
        case .newsletter: return "newsletter"
        case .aboutTheAuthor: return "about-the-author"
        }
    }

    /// The link text `EPUBTableOfContentsGenerator` uses for this entry in the
    /// Contents page — a generic label, not the rendered heading (Title Page's own
    /// heading is the book's actual title, not the words "Title Page", matching how a
    /// finished Scrivener export's own Contents page reads).
    public var contentsLabel: String {
        switch self {
        case .titlePage: return "Title Page"
        case .copyright: return "Copyright"
        case .dedication: return "Dedication"
        case .reviewAsk: return "A Note From the Author"
        case .newsletter: return "Newsletter"
        case .aboutTheAuthor: return "About the Author"
        }
    }

    /// Looks up which template (if any) a binder file corresponds to, by filename —
    /// used to decide whether a given front/back matter scene can offer "Regenerate
    /// from Template" at all.
    public static func matching(filename: String) -> FrontBackMatterTemplate? {
        allCases.first { $0.filename == filename }
    }

    public func content(for metadata: ProjectMetadata) -> String {
        switch self {
        case .titlePage:
            // `.title-page-heading` gets its own large/centered (not boxed-uppercase
            // chapter-style) treatment; `.centered-page` centers the subtitle/byline
            // under it instead of them sitting at the body's normal left margin.
            let subtitleLine = metadata.subtitle.isEmpty ? "" : "\(metadata.subtitle)\n\n"
            return """
                # \(metadata.title) {.title-page-heading #title-page}

                ::: {.centered-page}
                \(subtitleLine)[\(metadata.author)]{.byline}
                :::
                """

        case .copyright:
            // `.hidden-heading` keeps this a real, split-able, linkable H1 — a
            // finished Scrivener export's own Copyright page has no visible on-page
            // title either, just the legal text, centered — while still giving it a
            // page and a Contents entry. Wording/order matched against the Rook
            // Takes EPUB (§9.2) — the house style for Drew Calloway books.
            let isbnLine = metadata.isbn.isEmpty ? "" : "\nISBN: \(metadata.isbn)"
            return """
                # Copyright {.hidden-heading #copyright}

                ::: {.centered-page}
                *\(metadata.title)* is a work of fiction. Names, characters, places,
                and incidents are either products of the author's imagination or are
                used fictitiously. Any resemblance to actual persons, living or dead,
                events, or locales is entirely coincidental.

                Copyright © \(metadata.copyrightYear) by \(metadata.author)

                All rights reserved. No part of this book may be reproduced in any
                form or by any electronic or mechanical means, including information
                storage and retrieval systems, without written permission from the
                author, except for the use of brief quotations in a book review.
                \(isbnLine)
                :::
                """

        case .dedication:
            // `.hidden-heading` — same as Copyright: a real, linkable, split-able
            // heading that's never actually shown on the page. Rook Takes doesn't
            // use a dedication here at all — it opens with an epigraph (a quote +
            // attribution) instead, so that's the default; swap it for an actual
            // dedication by hand on books where that's what's wanted. `.dedication-page`
            // (alongside `.centered-page`) gets extra top margin of its own — an
            // epigraph reads better a few more lines down the page than Copyright's
            // block of legal text does.
            return """
                # Dedication {.hidden-heading #dedication}

                ::: {.centered-page .dedication-page}
                *"Quote goes here."*

                — Attribution
                :::
                """

        case .reviewAsk:
            // Hidden heading (only in the Contents link and the page's `<title>`) —
            // the visible "headline" is a bold first paragraph instead, matching the
            // Rook Takes EPUB's own review-ask page (§9.2). `.callout-heading` (a
            // nested fenced div, not just a class on the paragraph) gets its own
            // larger `margin-bottom` so the headline reads as a distinct line above
            // the body text, not just another paragraph in the same rhythm.
            return """
                # A Note From \(metadata.author) {.hidden-heading #review-ask}

                :::: {.centered-page}
                ::: {.callout-heading}
                **DID THIS BOOK KEEP YOU UP PAST YOUR BEDTIME?**
                :::

                If you enjoyed the ride, a quick review would mean the world. It
                doesn't have to be fancy, a sentence or two is plenty, and it really
                does help the next reader find their way to a good late-night
                thriller.

                Leave a review on *Amazon* or *Goodreads*.
                ::::
                """

        case .newsletter:
            return """
                # Join the Newsletter {.hidden-heading #newsletter}

                :::: {.centered-page}
                ::: {.callout-heading}
                **WANT TO STAY UP TO DATE ON ALL THINGS \(metadata.author.uppercased())?**
                :::

                Sign up for my newsletter and you'll get new release updates first,
                plus short stories that aren't published anywhere else. Not on
                Amazon, not for sale. Just for readers on the list.

                drewcalloway.com/#newsletter
                ::::
                """

        case .aboutTheAuthor:
            return """
                # About the Author {#about-the-author}

                **\(metadata.author)** writes crime thrillers from a small apartment
                in central Texas. A lifelong music lover and devoted people-watcher,
                he finds most of his best ideas in coffee shops, grocery lines, and
                other places where strangers cross paths. He's usually got
                headphones in, half-listening to a playlist, half-listening to
                something he probably wasn't meant to overhear.
                """
        }
    }
}
